source :rubygems

gem "sinatra"
#gem "logger"
#gem "haml"
#gem "sass"
#gem "heroku"
#gem "json"
gem "nokogiri"
gem "awesome_print"
#gem "dm-sqlite-adapter"
#gem "datamapper"

#gem "foursquare2"
#gem "multi_json"
#gem "oauth2"
